### ISSUE TITLE
BaseDAppCreation.md: Step 3 not clear enough

### ISSUE THREAD

**Issue by MaxKK** [crypti/crypti-dapps-docs#6]
>? Update current genesis block? (or make new one)

You need to elaborate more on this. What happens if the existing genesis block is retained? What does it mean for the developer if he makes a new one or he keeps the old one?

The `(or make new one)` should be a `(no to make a new one)`.

**Comment by karmacoma** [comment]
Please see: https://docs.google.com/a/crypti.me/document/d/1U8smOdfs63Sz-k-1QHTkVjdBmjGtVK9wHqGqBfiu5Tg/edit?usp=sharing

**Comment by crypti** [comment]
Closed
